language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - npm install -g elm

script:
  - cd server
  - cargo build --verbose
  - cargo test --verbose
  - cd ../client
  - elm package install -y
  - elm make Mortgage.elm
