[package]
name = "mortgage"
version = "0.1.0"
authors = ["Matt Thomson <mattjohnthomson@gmail.com>"]

[dependencies]
bodyparser = "*"
iron = "*"
mount = "*"
num = "*"
plugin = "*"
router = "*"
rustc-serialize = "*"
staticfile = "*"
